# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/AddNewSignalDialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AddSignalDialog(object):
    def setupUi(self, AddSignalDialog):
        AddSignalDialog.setObjectName("AddSignalDialog")
        AddSignalDialog.resize(280, 379)
        self.gridLayout = QtWidgets.QGridLayout(AddSignalDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(AddSignalDialog)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.radioButtonSin = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonSin.setChecked(True)
        self.radioButtonSin.setObjectName("radioButtonSin")
        self.verticalLayout_4.addWidget(self.radioButtonSin)
        self.radioButtonCos = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonCos.setObjectName("radioButtonCos")
        self.verticalLayout_4.addWidget(self.radioButtonCos)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.AmplitudeLabel = QtWidgets.QLabel(AddSignalDialog)
        self.AmplitudeLabel.setObjectName("AmplitudeLabel")
        self.verticalLayout.addWidget(self.AmplitudeLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalSliderAmplitude = QtWidgets.QSlider(AddSignalDialog)
        self.horizontalSliderAmplitude.setMinimum(1)
        self.horizontalSliderAmplitude.setMaximum(10)
        self.horizontalSliderAmplitude.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderAmplitude.setObjectName("horizontalSliderAmplitude")
        self.horizontalLayout.addWidget(self.horizontalSliderAmplitude)
        self.spinBoxAmplitude = QtWidgets.QSpinBox(AddSignalDialog)
        self.spinBoxAmplitude.setMinimumSize(QtCore.QSize(84, 0))
        self.spinBoxAmplitude.setMaximumSize(QtCore.QSize(57, 33))
        self.spinBoxAmplitude.setMinimum(1)
        self.spinBoxAmplitude.setMaximum(10)
        self.spinBoxAmplitude.setObjectName("spinBoxAmplitude")
        self.horizontalLayout.addWidget(self.spinBoxAmplitude)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.FrequencyLabel = QtWidgets.QLabel(AddSignalDialog)
        self.FrequencyLabel.setObjectName("FrequencyLabel")
        self.verticalLayout_2.addWidget(self.FrequencyLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalSliderFrequency = QtWidgets.QSlider(AddSignalDialog)
        self.horizontalSliderFrequency.setMinimum(1)
        self.horizontalSliderFrequency.setMaximum(3000)
        self.horizontalSliderFrequency.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderFrequency.setObjectName("horizontalSliderFrequency")
        self.horizontalLayout_2.addWidget(self.horizontalSliderFrequency)
        self.spinBoxFrequency = QtWidgets.QSpinBox(AddSignalDialog)
        self.spinBoxFrequency.setMinimumSize(QtCore.QSize(84, 0))
        self.spinBoxFrequency.setMaximumSize(QtCore.QSize(57, 33))
        self.spinBoxFrequency.setMinimum(1)
        self.spinBoxFrequency.setMaximum(3000)
        self.spinBoxFrequency.setObjectName("spinBoxFrequency")
        self.horizontalLayout_2.addWidget(self.spinBoxFrequency)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_2, 2, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.PhaseLabel = QtWidgets.QLabel(AddSignalDialog)
        self.PhaseLabel.setObjectName("PhaseLabel")
        self.verticalLayout_3.addWidget(self.PhaseLabel)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalSliderPhase = QtWidgets.QSlider(AddSignalDialog)
        self.horizontalSliderPhase.setMinimum(0)
        self.horizontalSliderPhase.setMaximum(2)
        self.horizontalSliderPhase.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderPhase.setObjectName("horizontalSliderPhase")
        self.horizontalLayout_3.addWidget(self.horizontalSliderPhase)
        self.spinBoxPhase = QtWidgets.QSpinBox(AddSignalDialog)
        self.spinBoxPhase.setMinimumSize(QtCore.QSize(84, 0))
        self.spinBoxPhase.setMaximumSize(QtCore.QSize(57, 33))
        self.spinBoxPhase.setMinimum(0)
        self.spinBoxPhase.setMaximum(2)
        self.spinBoxPhase.setObjectName("spinBoxPhase")
        self.horizontalLayout_3.addWidget(self.spinBoxPhase)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_3, 3, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(AddSignalDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 4, 0, 1, 1)

        self.retranslateUi(AddSignalDialog)
        self.buttonBox.accepted.connect(AddSignalDialog.accept)
        self.buttonBox.rejected.connect(AddSignalDialog.reject)
        self.horizontalSliderAmplitude.valueChanged['int'].connect(self.spinBoxAmplitude.setValue)
        self.spinBoxAmplitude.valueChanged['int'].connect(self.horizontalSliderAmplitude.setValue)
        self.horizontalSliderFrequency.valueChanged['int'].connect(self.spinBoxFrequency.setValue)
        self.spinBoxFrequency.valueChanged['int'].connect(self.horizontalSliderFrequency.setValue)
        self.horizontalSliderPhase.valueChanged['int'].connect(self.spinBoxPhase.setValue)
        self.spinBoxPhase.valueChanged['int'].connect(self.horizontalSliderPhase.setValue)
        QtCore.QMetaObject.connectSlotsByName(AddSignalDialog)

    def retranslateUi(self, AddSignalDialog):
        _translate = QtCore.QCoreApplication.translate
        AddSignalDialog.setWindowTitle(_translate("AddSignalDialog", "Dialog"))
        self.groupBox.setTitle(_translate("AddSignalDialog", "Signal Type"))
        self.radioButtonSin.setText(_translate("AddSignalDialog", "Sin"))
        self.radioButtonCos.setText(_translate("AddSignalDialog", "Cos"))
        self.AmplitudeLabel.setText(_translate("AddSignalDialog", "Amplitude"))
        self.FrequencyLabel.setText(_translate("AddSignalDialog", "Frequency"))
        self.PhaseLabel.setText(_translate("AddSignalDialog", "Phase"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddSignalDialog = QtWidgets.QDialog()
    ui = Ui_AddSignalDialog()
    ui.setupUi(AddSignalDialog)
    AddSignalDialog.show()
    sys.exit(app.exec_())

