# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/NewSignalDialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NewSignalDialog(object):
    def setupUi(self, NewSignalDialog):
        NewSignalDialog.setObjectName("NewSignalDialog")
        NewSignalDialog.resize(406, 426)
        self.gridLayout = QtWidgets.QGridLayout(NewSignalDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButtonPlot = QtWidgets.QPushButton(NewSignalDialog)
        self.pushButtonPlot.setObjectName("pushButtonPlot")
        self.horizontalLayout_4.addWidget(self.pushButtonPlot)
        self.pushButtonCancel = QtWidgets.QPushButton(NewSignalDialog)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout_4.addWidget(self.pushButtonCancel)
        self.gridLayout.addLayout(self.horizontalLayout_4, 4, 1, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.groupBox = QtWidgets.QGroupBox(NewSignalDialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.radioButtonSin = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonSin.setChecked(True)
        self.radioButtonSin.setObjectName("radioButtonSin")
        self.verticalLayout_4.addWidget(self.radioButtonSin)
        self.radioButtonCos = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonCos.setObjectName("radioButtonCos")
        self.verticalLayout_4.addWidget(self.radioButtonCos)
        self.radioButtonSquare = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonSquare.setObjectName("radioButtonSquare")
        self.verticalLayout_4.addWidget(self.radioButtonSquare)
        self.radioButtonSawTooth = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonSawTooth.setObjectName("radioButtonSawTooth")
        self.verticalLayout_4.addWidget(self.radioButtonSawTooth)
        self.horizontalLayout_6.addWidget(self.groupBox)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(NewSignalDialog)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.spinBoxFs = QtWidgets.QSpinBox(NewSignalDialog)
        self.spinBoxFs.setMaximum(65535)
        self.spinBoxFs.setObjectName("spinBoxFs")
        self.verticalLayout_5.addWidget(self.spinBoxFs)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        self.gridLayout.addLayout(self.horizontalLayout_6, 0, 0, 1, 2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.AmplitudeLabel = QtWidgets.QLabel(NewSignalDialog)
        self.AmplitudeLabel.setObjectName("AmplitudeLabel")
        self.verticalLayout.addWidget(self.AmplitudeLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalSliderAmplitude = QtWidgets.QSlider(NewSignalDialog)
        self.horizontalSliderAmplitude.setMinimum(1)
        self.horizontalSliderAmplitude.setMaximum(10)
        self.horizontalSliderAmplitude.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderAmplitude.setObjectName("horizontalSliderAmplitude")
        self.horizontalLayout.addWidget(self.horizontalSliderAmplitude)
        self.spinBoxAmplitude = QtWidgets.QSpinBox(NewSignalDialog)
        self.spinBoxAmplitude.setMinimumSize(QtCore.QSize(84, 0))
        self.spinBoxAmplitude.setMaximumSize(QtCore.QSize(57, 33))
        self.spinBoxAmplitude.setMinimum(1)
        self.spinBoxAmplitude.setMaximum(10)
        self.spinBoxAmplitude.setObjectName("spinBoxAmplitude")
        self.horizontalLayout.addWidget(self.spinBoxAmplitude)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.FrequencyLabel = QtWidgets.QLabel(NewSignalDialog)
        self.FrequencyLabel.setObjectName("FrequencyLabel")
        self.verticalLayout_2.addWidget(self.FrequencyLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalSliderFrequency = QtWidgets.QSlider(NewSignalDialog)
        self.horizontalSliderFrequency.setMinimum(1)
        self.horizontalSliderFrequency.setMaximum(3000)
        self.horizontalSliderFrequency.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderFrequency.setObjectName("horizontalSliderFrequency")
        self.horizontalLayout_2.addWidget(self.horizontalSliderFrequency)
        self.spinBoxFrequency = QtWidgets.QSpinBox(NewSignalDialog)
        self.spinBoxFrequency.setMinimumSize(QtCore.QSize(84, 0))
        self.spinBoxFrequency.setMaximumSize(QtCore.QSize(57, 33))
        self.spinBoxFrequency.setMinimum(1)
        self.spinBoxFrequency.setMaximum(3000)
        self.spinBoxFrequency.setObjectName("spinBoxFrequency")
        self.horizontalLayout_2.addWidget(self.spinBoxFrequency)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_2, 2, 0, 1, 2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.PhaseLabel = QtWidgets.QLabel(NewSignalDialog)
        self.PhaseLabel.setObjectName("PhaseLabel")
        self.verticalLayout_3.addWidget(self.PhaseLabel)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalSliderPhase = QtWidgets.QSlider(NewSignalDialog)
        self.horizontalSliderPhase.setMinimum(0)
        self.horizontalSliderPhase.setMaximum(2)
        self.horizontalSliderPhase.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderPhase.setObjectName("horizontalSliderPhase")
        self.horizontalLayout_3.addWidget(self.horizontalSliderPhase)
        self.spinBoxPhase = QtWidgets.QSpinBox(NewSignalDialog)
        self.spinBoxPhase.setMinimumSize(QtCore.QSize(84, 0))
        self.spinBoxPhase.setMaximumSize(QtCore.QSize(57, 33))
        self.spinBoxPhase.setMinimum(0)
        self.spinBoxPhase.setMaximum(2)
        self.spinBoxPhase.setObjectName("spinBoxPhase")
        self.horizontalLayout_3.addWidget(self.spinBoxPhase)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_3, 3, 0, 1, 2)

        self.retranslateUi(NewSignalDialog)
        self.horizontalSliderAmplitude.valueChanged['int'].connect(self.spinBoxAmplitude.setValue)
        self.spinBoxAmplitude.valueChanged['int'].connect(self.horizontalSliderAmplitude.setValue)
        self.horizontalSliderFrequency.valueChanged['int'].connect(self.spinBoxFrequency.setValue)
        self.spinBoxFrequency.valueChanged['int'].connect(self.horizontalSliderFrequency.setValue)
        self.horizontalSliderPhase.valueChanged['int'].connect(self.spinBoxPhase.setValue)
        self.spinBoxPhase.valueChanged['int'].connect(self.horizontalSliderPhase.setValue)
        self.radioButtonSquare.clicked['bool'].connect(self.horizontalSliderPhase.setDisabled)
        self.radioButtonSquare.clicked['bool'].connect(self.spinBoxPhase.setDisabled)
        self.radioButtonSawTooth.clicked['bool'].connect(self.horizontalSliderPhase.setDisabled)
        self.radioButtonSawTooth.clicked['bool'].connect(self.spinBoxPhase.setDisabled)
        self.radioButtonCos.clicked['bool'].connect(self.horizontalSliderPhase.setEnabled)
        self.radioButtonCos.clicked['bool'].connect(self.spinBoxPhase.setEnabled)
        self.radioButtonSin.clicked['bool'].connect(self.horizontalSliderPhase.setEnabled)
        self.radioButtonSin.clicked['bool'].connect(self.spinBoxPhase.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(NewSignalDialog)

    def retranslateUi(self, NewSignalDialog):
        _translate = QtCore.QCoreApplication.translate
        NewSignalDialog.setWindowTitle(_translate("NewSignalDialog", "Form"))
        self.pushButtonPlot.setText(_translate("NewSignalDialog", "Plot"))
        self.pushButtonCancel.setText(_translate("NewSignalDialog", "Cancel"))
        self.groupBox.setTitle(_translate("NewSignalDialog", "Signal Type"))
        self.radioButtonSin.setText(_translate("NewSignalDialog", "Sin"))
        self.radioButtonCos.setText(_translate("NewSignalDialog", "Cos"))
        self.radioButtonSquare.setText(_translate("NewSignalDialog", "Square"))
        self.radioButtonSawTooth.setText(_translate("NewSignalDialog", "SawTooth"))
        self.label.setText(_translate("NewSignalDialog", "Sampling Frecuency"))
        self.AmplitudeLabel.setText(_translate("NewSignalDialog", "Amplitude"))
        self.FrequencyLabel.setText(_translate("NewSignalDialog", "Frequency"))
        self.PhaseLabel.setText(_translate("NewSignalDialog", "Phase"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NewSignalDialog = QtWidgets.QWidget()
    ui = Ui_NewSignalDialog()
    ui.setupUi(NewSignalDialog)
    NewSignalDialog.show()
    sys.exit(app.exec_())

